[package]
name = "Reseaux"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
reqwest = { version = "0.12.14", features = ["cookies", "json"] }
regex = "1.11.1"
scraper = "0.23.1"